[package]
name = "json_normalizer"
version = "0.1.0"
authors = ["Hazim Salem <hsalem@certtech.com>"]
edition = "2018"

[dependencies]
serde_json = "*"

[lib]
name = "json_normalizer"
path = "src/lib/lib.rs"

[[bin]]
name = "json_normalizer_bin"
path = "src/bin/main.rs"